### ISSUE TITLE
submitted.log not created if not existing

### ISSUE THREAD

**Issue by brunetton** [acoustid/acoustid-fingerprinter#10]
The error message appears:

    Couldn't open cache file "/home/bruno/.cache/Acoustid/Fingerprinter/submitted.log" for reading 

To make it apparently okay, I had to 

    mkdir -p ~/.cache/Acoustid/Fingerprinter/
    touch ~/.cache/Acoustid/Fingerprinter/submitted.log

**Comment by lalinsky** [comment]
This is not an error, it's just a warning.
