### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by FFS1** [acoustid/acoustid-fingerprinter#13]
Hello Bruno,

accordingly to http://stackoverflow.com/questions/2558016/how-to-extract-the-lat-lng-of-pins-in-google-maps i kindly ask how it was possible for u to get the MID of a public available Google Map POI on a specific Webpage? I like to be able to download this file and Import in Google earth.

you wrote:

This doesn't works anymore. Now the trick is: google.com/maps/d/kml?mid={map_id} For example : google.com/maps/d/kml?mid=1lL6Ylpo7P3HnANcHTAzbH5hEx-E – brunetton Jun 8 '16 at 12:20 

help is much appreciate, thank you

**Comment by lalinsky** [comment]
This is not the right place to ask this question. :)
